// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Chart2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * temt6000meter;
extern lv_meter_indicator_t * temt6000indic;

extern lv_obj_t * sgp30meter;
extern lv_meter_indicator_t * sgp30indic;

extern lv_obj_t * tempmeter;
extern lv_meter_indicator_t * tempindic;

extern lv_obj_t * humimeter;
extern lv_meter_indicator_t * humiindic;

extern lv_obj_t * historylist;

extern lv_chart_series_t * mainser;

extern lv_obj_t * historylabel;
void ui_init(void);

LV_FONT_DECLARE(lv_font_Chinese_src_regular)

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
