// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

static void back_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    lv_scr_load(ui_Screen1);
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel7, lv_pct(100));
    lv_obj_set_height(ui_Panel7, lv_pct(15));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton2 = lv_btn_create(ui_Panel7);
    lv_obj_set_height(ui_ImgButton2, 32);
    lv_obj_set_width(ui_ImgButton2, 72);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_LEFT_MID);
    lv_obj_t * backlabel = lv_label_create(ui_ImgButton2);
    lv_label_set_text(backlabel, "< 返回");
    lv_obj_set_style_text_font(backlabel,&lv_font_Chinese_src_regular,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(backlabel);
    //lv_img_set_src(ui_ImgButton1, LV_SYMBOL_BACKSPACE);
    lv_obj_add_event_cb(ui_ImgButton2,back_event_handler,LV_EVENT_CLICKED,NULL);

    ui_Label3 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "历史");
    lv_obj_set_style_text_font(ui_Label3,&lv_font_Chinese_src_regular,LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel8, lv_pct(100));
    lv_obj_set_height(ui_Panel8, lv_pct(85));
    lv_obj_set_align(ui_Panel8, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    //lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart2 = lv_chart_create(ui_Panel8);
    lv_obj_set_width(ui_Chart2, 200);
    lv_obj_set_height(ui_Chart2, 100);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    mainser = lv_chart_add_series(ui_Chart2, lv_palette_main(LV_PALETTE_BLUE), LV_CHART_AXIS_PRIMARY_Y);
    //lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    //lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
    //                                                             LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    //lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);


    historylabel = lv_label_create(ui_Panel8);
    lv_label_set_long_mode(historylabel, LV_LABEL_LONG_WRAP);
}
